Show red warning when failing to compile

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -1,3 +1,10 @@
 #!/bin/bash
-set -e
+
 g++ -Wall -W -Werror -std=c++11 $1 -o $2
+
+status=$?
+if [ $status -ne 0 ] 
+then
+    echo -e "\e[101mFailed to compile!\e[0m"
+    exit $status
+fi
